### PR TITLE
Feature 154 parameter scale

### PR DESCRIPTION
**Pull request by elbaraim**
reference to 
### Clarify meaning of observableTransformation and parameterScale #154 

- Check positivity (>=0) of all entries in `nominalValue`, `upperBound` and `lowerBound` from parameter table.
- Corresponding test created.

### CODE REVIEW

**Comment by elbaraim** [comment]
> Hmm. This seems to be redundant with https://github.com/ICB-DCM/PEtab/pull/169/files, isn't it?

I think the positivity of `nominalValues` it was not implemented (?)

**Comment by dweindl** [comment]
> > Hmm. This seems to be redundant with https://github.com/ICB-DCM/PEtab/pull/169/files, isn't it?
> 
> I think the positivity of `nominalValues` it was not implemented (?)

That's true, but they only need to be positive if log-scale is selected.

**Comment by elbaraim** [comment]
> > > Hmm. This seems to be redundant with https://github.com/ICB-DCM/PEtab/pull/169/files, isn't it?
> > 
> > 
> > I think the positivity of `nominalValues` it was not implemented (?)
> 
> That's true, but they only need to be positive if log-scale is selected.

Totally makes sense that they need to be positive if log-scale. However, shouldn't we still infer positivity even in linear-scale? Negative parameters do not biologically make sense... What do you think about this?

**Comment by dweindl** [comment]
> Negative parameters do not biologically make sense... What do you think about this?

That is true for rate constants, volumes, etc.. However, there may well be all kinds of other parameters for which it may make sense to be negative.

**Comment by FFroehlich** [comment]
> > Negative parameters do not biologically make sense... What do you think about this?
> 
> That is true for rate constants, volumes, etc.. However, there may well be all kinds of other parameters for which it may make sense to be negative.

Energies, Charges, ...

**Comment by elbaraim** [comment]
True! Thank you for the feedback then I would suggest to remove this PR

**Pull request closed without merging**
