### PR TITLE
Next PEtab version

### LINKED ISSUE #124: Why is there a version 0.0.0a15 on PyPI while master is at 0.0.0a14?
This should not have happened. There is no 0.0.0a15 tag, github or zenodo release. Skip 0.0.0a15 for next version bump.

### PR DESCRIPTION
**Pull request by paulstapor**
* Adding a new visualization framework (using a visualization specification file)
 * added new columns to the measurement table: datasetId
 * adding use of the prior column
 * Closes #124 
* Fix, test and deprecate petab.sbml.constant_species_to_parameters
* fix deploy

### CODE REVIEW

**Comment by dweindl** [comment]
Wait for tonight? Otherwise good.

**Comment by paulstapor** [comment]
Maybe after the prior stuff merge (useful for parPE)? Or before?

**Comment by paulstapor** [comment]
Okay, I can't merge that one, I'm not authorized, as I see... Please, somebody else o that... ;)

**Comment by yannikschaelte** [comment]
I'm also not authorized (any more?)

**Comment by dweindl** [comment]
I set @MerktSimon @elbaraim @erikadudki as maintainers as recently discussed. Please merge and create new release.

**Pull request merged**
